- packages/client/babel.config.js
- packages/client/constants/storage_keys.ts
- packages/client/gateways/auth_gateway.ts
- packages/client/gateways/request.ts
- packages/client/navigation/LinkingConfiguration.ts
- packages/client/navigation/index.tsx
- packages/client/screens/SignInScreen.tsx
- packages/client/screens/SignUpScreen.tsx
- packages/client/types.tsx
- added signin frontend page
- that's it
> CRYP-51: Added signin frontend page

- packages/client/screens/SignUpScreen.tsx
> CRYP-49: Increase sign up password inputs icon size to 20

- packages/client/screens/SignInScreen.tsx
> CRYP-51: Increase sign in password input icon size to 20

- packages/client/navigation/LinkingConfiguration.ts
- packages/client/navigation/index.tsx
- packages/client/screens/HomeScreen.tsx
- packages/client/screens/SettingsScreen.tsx
- packages/client/types.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-95
- Add settings screen
- Add screen to navigation
- Add header styling for blank page
> CRYP-95: add basic settings page and navigation

- packages/api/src/gateways/eth_edge_gateway.ts
- packages/api/src/wallets/guards/authorization.guard.ts
- packages/api/src/wallets/wallets.controller.ts
- packages/api/src/wallets/wallets.service.ts
- packages/common/src/helpers/request.ts
- packages/common/src/requests/get_wallet_request.ts
- packages/common/src/validations/get_wallets_schema.ts
- added GET users/:id/wallets endpoint to api returns a list of wallets
- refactored request gateway to support methods without body (get, delete)
> CRYP-62: Create backend API for getting a users wallets

- packages/api/src/wallets/wallets.service.ts
- packages/common/src/domain/entities/wallet.ts
- packages/common/src/errors/error_messages.ts
- packages/common/src/helpers/request.ts
- packages/common/src/validations/create_wallet_schema.ts
- packages/eth-edge/src/controllers/wallets.controller.ts
- packages/eth-edge/src/services/wallets.service.ts
- added eth edge GET users/:id/wallets with alchemy integration
- refactored eth edge wallet service create method to check if the wallet exist in node before creating it in the database
> CRYP-71: create eth edge api for getting users wallets

- packages/common/src/domain/entities/transaction.ts
- packages/common/src/errors/error_messages.ts
- packages/eth-edge/src/modules/app.module.ts
- packages/eth-edge/src/modules/transactions.module.ts
- packages/eth-edge/src/modules/wallets.module.ts
- packages/eth-edge/src/services/alchemy_node.service.ts
- packages/eth-edge/src/services/transactions.service.ts
- packages/eth-edge/src/services/wallets.service.ts
Added transaction entity and backfilled them once a new account is added
> CRYP-69: Ethereum wallet transactions backfilling

- packages/client/components/SignOutButton.tsx
- packages/client/screens/HomeScreen.tsx
- packages/client/screens/SettingsScreen.tsx
- packages/client/services/storage_service.ts
- packages/client/theme/components/button.ts
> CRYP-23: Implement signout button and functionality on settings page

- packages/eth-edge/src/services/alchemy_node.service.ts
- packages/eth-edge/src/services/transactions.service.ts
Refactored the backfill method and how we get the transactions from alchemy.
> CRYP-159: Refactor backfill method

- packages/api/src/gateways/edge-gateway/abstract_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/btc_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/edge_gateway_strategy_factory.ts
- packages/api/src/gateways/edge-gateway/eth_edge_gateway_strategy.ts
- packages/api/src/modules/wallets.module.ts
- packages/api/src/services/wallets.service.ts
- packages/client/babel.config.js
- packages/client/metro.config.js
- packages/common/src/utils/gateway/abstract_gateway.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-115
- Introduce strategy pattern for the edge gateways and strategy factory
- Refactor API wallet service methods to use factory instead of gateway strategy directly
> CRYP-115: use strategy and factory patterns in gateway

- packages/client/navigation/index.tsx
- packages/client/screens/WelcomeScreen.tsx
- packages/client/tests/system/sign_up.e2e.ts
- packages/client/tests/system/utils/open_app_for_debug_build.js
- packages/client/tests/system/utils/test_utils.ts
- packages/client/tests/system/welcome_page.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-100
- Add system test for welcome page
- Update sign up system test for new welcome page flow
> CRYP-100: welcome screen system test

- packages/api/src/controllers/transactions.controller.ts
- packages/api/src/gateways/edge-gateway/abstract_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/btc_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/eth_edge_gateway_strategy.ts
- packages/api/src/modules/app.module.ts
- packages/api/src/modules/transactions.module.ts
- packages/api/src/services/transactions.service.ts
- packages/api/src/services/wallets.service.ts
- packages/client/gateways/transactions_gateway.ts
- packages/common/src/requests/get_transaction_request.ts
- packages/common/src/validations/get_transactions_schema.ts
- packages/eth-edge/src/controllers/transactions.controller.ts
- packages/eth-edge/src/modules/transactions.module.ts
- packages/eth-edge/src/modules/wallets.module.ts
- packages/eth-edge/src/services/transactions.service.ts
- packages/eth-edge/src/services/wallets.service.ts
Added ability to get transactions for a user in the eth architecture
> CRYP-74: implement backend api for getting a users transactions

- packages/client/components/Transaction.tsx
- packages/client/components/TransactionList.tsx
- packages/client/components/TransactionListItem.tsx
Added transaction list with the ability to display date separators
> Cryp-28: list of all transactions associated to each of my eth wallets

- packages/api/src/controllers/users.controller.ts
- packages/client/App.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-101
> CRYP-101: auto sign out when user not found

- .eslintrc.js
- .github/workflows/ci.yml
- .gitignore
- docker-compose.sonarqube.yml
- package.json
- packages/api/jest-config-unit.json
- packages/api/jest-config.json
- packages/api/package.json
- packages/eth-edge/jest-config-unit.json
- packages/eth-edge/jest-config.json
- packages/eth-edge/package.json
- sonarqube-scanner.js
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-106
- Fix code coverage reporting for integration tests
- Setup sonarqube in docker and scripts
> CRYP-106: setup sonarqube

- packages/client/components/TransactionDetails.tsx
- packages/client/components/TransactionList.tsx
- packages/client/components/TransactionListItem.tsx
- packages/client/components/icons/faArrowRightCustom.tsx
- packages/client/components/icons/faMagnifyingGlassCustom.tsx
- packages/client/navigation/index.tsx
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/services/transaction_service.ts
- packages/client/types.tsx
Added transaction list screen and connected all transaction screens with the navigation. I also ran the linter
> CRYP-28: list of all transactions associated to each of my ethereum wallets

- packages/client/components/TransactionList.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/tests/system/transaction_List_page.e2e.ts
I added the system tests for the transaction list page
> CRYP-130: System tests for transaction list page

- packages/client/.detoxrc.json
JIRA: https://cryptify.atlassian.net/browse/CRYP-20
- Update detox.json file with the update ios config
> CRYP-20: Update detox config

- packages/client/App.tsx
- packages/client/android/app/build.gradle
- packages/client/components/TransactionDetails.tsx
- packages/client/components/TransactionList.tsx
- packages/client/components/TransactionListItem.tsx
- packages/client/components/wallets-list/WalletsListAccordion.tsx
- packages/client/package.json
- packages/client/screens/WalletDetailsScreen.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/services/address_service.ts
- packages/client/services/transaction_service.ts
- packages/client/types.tsx
- packages/common/src/utils/string_utils.ts
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-26
> CRYP-26: refactor to single get transactions call and fix dates

- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/tests/system/wallet_details_page.e2e.ts
The system tests should work and are currently ensuring all elements are present for the wallet details page. Could not fully test due to M1 issues
> CRYP-136: System test for wallet details page

- packages/api/test/unit/transactions/transactions.controller.spec.ts
- packages/api/test/unit/wallets/wallets.controller.spec.ts
> CRYP-000: Added Api unit test

- packages/common/src/utils/currency_utils.ts
- packages/eth-edge/src/modules/transactions.module.ts
- packages/eth-edge/src/modules/wallets.module.ts
- packages/eth-edge/src/services/alchemy_node_facade.service.ts
- packages/eth-edge/src/services/transactions.service.ts
- packages/eth-edge/src/services/wallets.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-207
- Add function that converts from scientific notation
- Use alchemy node service as facade to not expose type not owned by us
> CRYP-207: fix alchemy scientific notation bug

- packages/client/tests/system/CRYP-100_welcome_page.e2e.ts
- packages/client/tests/system/CRYP-101_home_page.e2e.ts
- packages/client/tests/system/CRYP-108_wallet_qr_code_page.e2e.ts
- packages/client/tests/system/CRYP-21_sign_up.e2e.ts
- packages/client/tests/system/CRYP-22_sign_in.e2e.ts
- packages/client/tests/system/CRYP-23_sign_out.e2e.ts
- packages/client/tests/system/CRYP-24_add_wallet.e2e.ts
- packages/client/tests/system/CRYP-26_wallet_details_page.e2e.ts
- packages/client/tests/system/CRYP-27_wallets_list.e2e.ts
- packages/client/tests/system/CRYP-28_transaction_list_page.e2e.ts
- packages/client/tests/system/CRYP-30_transaction_details_page.e2e.ts
- packages/client/tests/system/CRYP-94_tab_bar.e2e.ts
- packages/client/tests/system/CRYP-95_settings_page.e2e.ts
- packages/client/tests/system/utils/test_utils.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-125
> CRYP-125: Add pause and waits in system tests

- sonarqube-scanner.js
JIRA: https://cryptify.atlassian.net/browse/CRYP-106
> CRYP-106: Update SQ script

- .github/workflows/ci.yml
- docker-compose.yml
- package.json
- packages/btc-edge/.env
- packages/btc-edge/.env.test
- packages/btc-edge/jest-config-unit.json
- packages/btc-edge/jest-config.json
- packages/btc-edge/nest-cli.json
- packages/btc-edge/package.json
- packages/btc-edge/src/controllers/base.controller.ts
- packages/btc-edge/src/main.ts
- packages/btc-edge/src/modules/app.module.ts
- packages/btc-edge/src/modules/base.module.ts
- packages/btc-edge/test/integration/base_api.spec.ts
- packages/btc-edge/test/unit/controllers/base.controller.spec.ts
- packages/btc-edge/tsconfig.build.json
- packages/btc-edge/tsconfig.json
- packages/docker/btc-edge.Dockerfile
- sonarqube-scanner.js
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-110
- Add BtcEdge service
- Create new docker file
- Update dockercompose file
- Update sonarqube
> CRYP-110: Setup BtcEdge API

- packages/api/src/services/users.service.ts
- packages/eth-edge/src/services/transactions.service.ts
- updated to insert for user Service
- updated comments in eth-edge transaction service
> CRYP-117: Refactor services to use insert and find instead of save

- .eslintrc.js
- packages/common/package.json
- packages/common/src/utils/currency_utils.ts
- packages/common/src/utils/wav-in.js
- packages/common/src/utils/wav.js
- packages/common/src/utils/wav.ts
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-120
> CRYP-120: fix wallet validation lib for react native and m1

- packages/client/components/TransactionDetails.tsx
- packages/client/tests/system/CRYP-30_transaction_details_page.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-225
- Moved `Gas Price` and `Gas Limit` to `Other Details` section
- Removed `Transaction Fee` section
> CRYP-225: Refactor ETH transaction details by moving transaction fee info to other details section

- packages/client/components/icons/regular/farPencil.tsx
- packages/client/gateways/tags_gateway.ts
- packages/client/navigation/index.tsx
- packages/client/screens/EditTagScreen.tsx
- packages/client/screens/TagsSettingsScreen.tsx
- packages/client/types.tsx
> CRYP 178: edit user tag frontend

- packages/client/screens/EditTagScreen.tsx
> CRYP-175: delete tag from tags list

- packages/btc-edge/src/services/transactions_service.ts
- packages/eth-edge/src/modules/transactions.module.ts
- packages/eth-edge/src/services/transactions.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-234
- Add check to skip backfill if wallet already exists
> CRYP-234: Add check to early return if wallet is already added

- packages/btc-edge/src/services/transactions_service.ts
- packages/eth-edge/src/services/transactions.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-234
> CRYP-234: Update conditional check when skipping transactions

- packages/client/package.json
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-29
> CRYP-29: Do major minor pin instead of only major pin

- packages/api/package.json
- packages/api/src/controllers/users.controller.ts
- packages/api/src/services/users.service.ts
- packages/api/test/integration/user_api.spec.ts
- packages/btc-edge/package.json
- packages/common/src/db/seed_db.ts
- packages/common/src/requests/update_user_request.ts
- packages/common/src/validations/update_user_schema.ts
- packages/eth-edge/package.json
JIRA: https://cryptify.atlassian.net/browse/CRYP-40
- Create new endpoint that allows updating a users attributes, this uses the active record design pattern through typeorm
This will only be used right now to update a users notification preferences but can be used to update other attributes in the future.
> CRYP-40: create endpoint to update notification prefs

- packages/client/components/TransactionDetails.tsx
- packages/client/components/transactions-list/TransactionListItem.tsx
- packages/client/components/wallets-list/WalletsListAccordion.tsx
- packages/client/screens/WalletOverviewScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-40
> CRYP-40: Fix imports that weren't updated

- packages/client/components/TransactionDetails.tsx
- packages/client/components/wallets-list/WalletsList.tsx
- packages/client/screens/WalletOverviewScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-188
Fixes an issue where the UI would display no wallets or no transactions to the user while the application was still loading the data from the API. Now the section will remain blank while the API request is still loading / in progress.
> CRYP-188: fix no transactions / wallets being displayed while loading

- packages/client/screens/AddTagsScreen.tsx
- packages/client/screens/EditTagScreen.tsx
- packages/client/screens/SettingsScreen.tsx
- packages/client/screens/TagsSettingsScreen.tsx
- packages/client/tests/system/CRYP-175_delete_tag.e2e.ts
- packages/client/tests/system/CRYP-177_tags_list.e2e.ts
- packages/client/tests/system/CRYP-178_edit_tag.e2e.ts
- packages/client/tests/system/CRYP-35_add_tag.e2e.ts
- packages/client/tests/system/config.json
- packages/common/src/db/seed_db.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-177
JIRA: https://cryptify.atlassian.net/browse/CRYP-35
JIRA: https://cryptify.atlassian.net/browse/CRYP-178
JIRA: https://cryptify.atlassian.net/browse/CRYP-175
Add system tests for tag CRUD user stories
> CRYP-177: create system tests for tags

- packages/client/screens/FilterScreen.tsx
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/tests/system/CRYP-164_filter_bitcoin_transactions.e2e.ts
- packages/client/tests/system/CRYP-29_filter_ethereum_transactions.e2e.ts
- packages/client/types.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-29
JIRA: https://cryptify.atlassian.net/browse/CRYP-164
- Add system tests for filtering bitcoin and ethereum transactions
- Fixed some bugs with filtering, filters not showing up after applying and navigating back to screen, reset button not working, incorrect button disabled state
> CRYP-29: system test for filtering Bitcoin and Ethereum transactions

- packages/client/components/transactions-list/SortTransactionListComponent.tsx
- packages/client/tests/system/CRYP-166_sort_bitcoin_transactions.e2e.ts
- packages/client/tests/system/CRYP-31_sort_ethereum_transactions.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-31
JIRA: https://cryptify.atlassian.net/browse/CRYP-166
- Added systems tests for sorting bitcoin and ethereum transactions
- Added related test ids
- Fixed issue wherre action sheet wouldn't automatically close on select
> CRYP-166: system test sorting Bitcoin and Ethereum transactions

- packages/btc-edge/src/services/transactions_service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-179
- Update btc-edge to use the tags relation
> CRYP-179: Add transaction tagging to Bitcoin transactions

- packages/client/screens/NotificationsScreen.tsx
- packages/client/tests/system/CRYP-41_update_notification_preferences.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-41
> CRYP-41: Add system test for updating notification preferences

- packages/client/components/TransactionDetails.tsx
- packages/client/screens/AddTransactionTagsScreen.tsx
- packages/client/screens/TransactionTagsScreen.tsx
- packages/client/tests/system/CRYP-179_bitcoin_transaction_tagging.e2e.ts
- packages/client/tests/system/CRYP-33_ethereum_transaction_tagging.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-33
JIRA: https://cryptify.atlassian.net/browse/CRYP-179
> CRYP-33: system test for Bitcoin and Ethereum transaction tagging

- packages/client/tests/system/CRYP-232_transaction_history_report.e2e.ts
https://cryptify.atlassian.net/browse/CRYP-232
> CRYP-232: Add system test for transaction history report

- packages/client/tests/system/CRYP-108_ethereum_wallet_share.e2e.ts
- packages/client/tests/system/CRYP-168_bitcoin_wallet_share.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-168
> CRYP-168: Add wallet share system tests

- packages/client/components/TransactionDetailsActionSheet.tsx
- packages/client/navigation/index.tsx
- packages/client/screens/contacts/AddContactScreen.tsx
- packages/client/screens/contacts/ContactsListScreen.tsx
- packages/client/tests/system/CRYP-194_contacts_list.e2e.ts
- packages/client/tests/system/CRYP-34_create_contact.e2e.ts
- packages/client/tests/system/CRYP-36_wallet_contact_tagging.e2e.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-34
JIRA: https://cryptify.atlassian.net/browse/CRYP-194
JIRA: https://cryptify.atlassian.net/browse/CRYP-36
> CRPY-34: system test for contacts

- packages/client/tests/system/CRYP-34_create_contact.e2e.ts
- packages/common/src/db/seed_db.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-34
> CRYP-34: update system test

- packages/api/src/controllers/contacts.controller.ts
- packages/api/test/integration/contacts_api.spec.ts
- packages/api/test/integration/tags_api.spec.ts
- packages/api/test/integration/transactions_api.spec.ts
- packages/api/test/integration/user_api.spec.ts
- packages/api/test/integration/wallet_api.spec.ts
- Added integration tests for API covering all services, controllers, etc
> CRYP-000: Add api integration tests

- packages/eth-edge/src/modules/transactions.module.ts
- packages/eth-edge/src/modules/wallets.module.ts
- packages/eth-edge/src/services/alchemy_decorator.ts
- packages/eth-edge/src/services/alchemy_node_facade.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-179
> CRYP-179: allow mocking alchemy sdk

- packages/btc-edge/src/services/transaction_watcher_service.ts
- packages/btc-edge/src/services/wallets.service.ts
- packages/btc-edge/test/integration/base_api.spec.ts
- packages/btc-edge/test/integration/transactions_api.spec.ts
- packages/btc-edge/test/integration/wallet_api.spec.ts
- packages/btc-edge/test/unit/gateways/so_chain_gateway.spec.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-166
> CRYP-166: Add BTC-edge integration tests

- packages/api/src/services/users.service.ts
- packages/api/test/integration/user_api.spec.ts
- packages/api/test/unit/contacts/contacts.controller.spec.ts
- packages/api/test/unit/tags/tags.controller.spec.ts
- packages/api/test/unit/users/users.controller.spec.ts
- packages/api/test/unit/wallets/wallets.controller.spec.ts
- packages/btc-edge/test/unit/controllers/wallets.controller.spec.ts
- packages/common/src/domain/entities/user.ts
- packages/common/src/domain/role.ts
- packages/common/src/requests/update_user_request.ts
- packages/common/src/validations/update_user_schema.ts
- packages/eth-edge/test/unit/wallets/wallets.controller.spec.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-247
> CRYP-247: update db schema for pro mode

- packages/client/components/transaction-details/BitcoinTransactionDetails.tsx
- packages/client/components/transaction-details/EthereumTransactionDetails.tsx
- packages/client/components/transaction-details/TransactionDetails.tsx
- packages/common/src/domain/role.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-248
> CRYP-248: Integrate pro mode with transaction details

- packages/client/screens/account/AccountScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-202
> CRYP-202: Account information screen

- packages/client/components/transaction-details/TransactionDetails.tsx
- packages/client/components/transactions-list/TransactionListItem.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/services/transaction_service.ts
> CRYP-228: added ethereum transaction fee amount

- packages/client/components/contacts/CollapsibleFormSection.tsx
- packages/client/components/contacts/ContactsForm.tsx
- packages/client/components/icons/regular/farCirclePlus.tsx
- packages/client/screens/contacts/AddContactScreen.tsx
- packages/client/screens/contacts/EditContactScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-191
- Updated header button for edit contact page
- Cancel
- Done
- Moved delete button into proper component
- Moved edit on press functionality into proper component
- Fixed some styling issues in the form components including using the proper icon
> CRYP-191: fix edit contact button

- packages/api/src/services/transactions.service.ts
- packages/common/src/domain/entities/transaction.ts
- packages/eth-edge/src/services/alchemy_node_facade.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-305
> CRYP-305: transaction builder pattern

- packages/client/components/WalletDetailsComponent.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/screens/WalletSettingsScreen.tsx
Story: https://cryptify.atlassian.net/browse/CRYP-267?atlOrigin=eyJpIjoiN2I0MDUzZDBkYjFiNDAzNWFmMjc5NzRhNWI5NjQ1Y2IiLCJwIjoiaiJ9
Note: Ignore branch name, made PR changes on the wrong branch - it's the exact same as the previous PR (#201) but I forgot to switch branches / change branch name prior to commits. Please forgive me
> CRYP-267: ETH wallet details overview in settings tab

- packages/api/src/controllers/filters.controller.ts
- packages/api/src/services/filters.service.ts
- packages/common/src/db/data_source_options.ts
- packages/common/src/domain/entities/filter.ts
- packages/common/src/domain/entities/user.ts
- packages/common/src/errors/error_messages.ts
- packages/common/src/validations/create_filter_schema.ts
- packages/common/src/validations/delete_filter_schema.ts
- packages/common/src/validations/get_filters_schema.ts
- packages/eth-edge/src/services/alchemy_node_facade.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-32
- Add Filter entity
- Add CRD API for filter along with error handling
- Add API parameter validation
- Logic for handling relative filter date ranges
> CRYP-32: Saved filters CRUD API

- packages/api/src/controllers/filters.controller.ts
- packages/api/src/modules/app.module.ts
- packages/api/src/modules/filters.module.ts
- packages/api/src/services/filters.service.ts
- packages/client/components/SaveFilterActionSheet.tsx
- packages/client/components/WalletDetailsComponent.tsx
- packages/client/components/icons/regular/farBookmark.tsx
- packages/client/components/icons/solid/fasBookmark.tsx
- packages/client/components/transaction-details/TransactionDetails.tsx
- packages/client/components/transaction-details/TransactionDetailsActionSheet.tsx
- packages/client/gateways/filters_gateway.ts
- packages/client/navigation/index.tsx
- packages/client/package.json
- packages/client/screens/FilterScreen.tsx
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/screens/WalletSettingsScreen.tsx
- packages/client/screens/filters/FilterScreen.tsx
- packages/client/screens/filters/SavedFiltersScreen.tsx
- packages/client/screens/reports/TransactionHistoryReportScreen.tsx
- packages/client/types.tsx
- packages/common/src/domain/entities/filter.ts
- packages/common/src/validations/create_filter_schema.ts
- packages/common/src/validations/delete_filter_schema.ts
- packages/common/src/validations/get_filters_schema.ts
- yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-32
- Add frontend screen for selecting a saved filter
- Add actionsheet save filter form
- Add swipe to delete filters
- Keyboard issue on action sheet blocks it while types, not sure how to fix
> CRYP-32: saved filters frontend

- packages/client/components/SaveFilterActionSheet.tsx
- packages/client/components/transactions-list/TransactionsList.tsx
- packages/client/hooks/useKeyboardBottomInset.ts
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/screens/WalletOverviewScreen.tsx
- packages/client/screens/filters/FilterScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-32
- Fix keyboard handling with action sheet with keyboard input
- Fix minor stlying bugs in transaction list chips
- Update the rendering of the transaction list
> CRYP-32: fix action sheet hidden by keyboard

- packages/client/navigation/index.tsx
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/screens/filters/FilterScreen.tsx
- packages/client/screens/filters/FilterTagScreen.tsx
- packages/client/services/filter_service.ts
- packages/client/types.tsx
> CRYP-37: As a User, I want to filter my Ethereum wallet transactions by tag, so that I can search for specific transaction characteristics

- packages/client/screens/WalletSettingsScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-265
- Add BTC wallet format
- Tested screen to make sure everything is working and matches mocks for BTC
> CRYP-265: bitcoin wallet details settings screen

- packages/btc-edge/src/services/transactions_service.ts
- packages/eth-edge/src/services/transactions.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-307
- Remove the dependency on wallet balance for finding all transactions for a user, this involves decoupling the balance and txn api
> CRYP-307: Refactor btc-edge and eth-edge find all txn api

- packages/client/components/contacts/CollapsibleFormSection.tsx
- packages/client/components/list/MultiLineListItem.tsx
- packages/client/components/tags/TagItem.tsx
- packages/client/components/tags/TagsGallery.tsx
- packages/client/components/transaction-details/TransactionDetails.tsx
- packages/client/components/wallets-list/WalletsListAccordion.tsx
- packages/client/gateways/abstract_api_gateway.ts
- packages/client/screens/TransactionsListScreen.tsx
- packages/client/screens/add-wallet/AddWalletSelectionScreen.tsx
- packages/client/screens/filters/FilterContactScreen.tsx
- packages/client/screens/filters/FilterScreen.tsx
- packages/client/screens/filters/FilterTagScreen.tsx
- packages/client/screens/reports/TransactionHistoryReportScreen.tsx
- packages/client/services/filter_service.ts
- packages/client/services/transaction_service.ts
- packages/common/src/utils/notifications/transaction_notification_service.ts
- packages/common/src/validations/password_schema.ts
- packages/common/src/validations/sign_up_schema.ts
- packages/common/src/validations/update_user_schema.ts
- packages/eth-edge/src/controllers/transactions.controller.ts
- sonarqube-scanner.js
JIRA: https://cryptify.atlassian.net/browse/CRYP-308
- Cleaned up remaining code smells
- Update SQ config to ignore certain smells like TODOs that we don't want warnings / errors for
> CRYP-308: Cleanup all code smells

- packages/api/src/controllers/wallets.controller.ts
- packages/api/src/gateways/edge-gateway/abstract_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/btc_edge_gateway_strategy.ts
- packages/api/src/gateways/edge-gateway/eth_edge_gateway_strategy.ts
- packages/api/src/services/wallets.service.ts
- packages/client/gateways/wallets_gateway.ts
- packages/client/screens/WalletSettingsScreen.tsx
- packages/common/src/requests/update_wallet_request.ts
- packages/common/src/validations/update_wallet_schema.ts
- packages/eth-edge/src/controllers/wallets.controller.ts
- packages/eth-edge/src/services/wallets.service.ts
-Added frontend for wallet name edit
-added backend for eth
> CRYP-200: As a User, I want to edit an Ethereum wallet, so that I can change the wallet name

- packages/btc-edge/src/controllers/wallets.controller.ts
- packages/btc-edge/src/services/wallets.service.ts
> CRYP-200: As a User, I want to edit a Bitcoin wallet, so that I can change the wallet name

- packages/client/screens/SignInScreen.tsx
- packages/client/screens/SignUpScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-332
- Move the first name and last name form fields from the same line to each having their own line
- Change the title font weight for both the Sign Up and Sign In screens to semibold to match UI mockup
> CRYP-332: Refactor Sign Up screen to decuple first last name form fields to separate lines

- packages/api/src/modules/users.module.ts
- packages/api/src/services/authentication.service.ts
- packages/api/src/services/users.service.ts
- packages/api/test/integration/auth_api.spec.ts
- packages/api/test/integration/user_api.spec.ts
- packages/btc-edge/test/integration/wallet_api.spec.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-203
> CRYP-203: Auth and user integration tests

- packages/api/test/integration/filters_api.spec.ts
- packages/performance-tests/src/tests/find_contacts_and_tags_for_wallet_flow.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-32
> CRYP-32: Saved filters integration tests

- packages/api/test/integration/contacts_api.spec.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-263
> CRYP-263: Add Integration tests for contacts

- packages/client/components/list/MultiLineListItem.tsx
- packages/client/tests/system/CRYP-162_bitcoin_transaction_details.e2e.ts
- packages/client/tests/system/CRYP-191_edit_contact.e2e.ts
- packages/client/tests/system/CRYP-192_delete_contact.e2e.ts
- packages/client/tests/system/CRYP-195_filter_bitcoin_transactions_by_tag.e2e.ts
- packages/client/tests/system/CRYP-198_filter_ethereum_transactions_by_contact.e2e.ts
- packages/client/tests/system/CRYP-199_filter_bitcoin_transactions_by_contact.e2e.ts
- packages/client/tests/system/CRYP-200_edit_bitcoin_wallet.e2e.ts
- packages/client/tests/system/CRYP-201_edit_ethereum_wallet.e2e.ts
- packages/client/tests/system/CRYP-202_view_user_account.e2e.ts
- packages/client/tests/system/CRYP-203_update_user_account.e2e.ts
- packages/client/tests/system/CRYP-204_delete_account.e2e.ts
- packages/client/tests/system/CRYP-228_ethereum_transaction_fee.e2e.ts
- packages/client/tests/system/CRYP-247_pro_mode_toggle.e2e.ts
- packages/client/tests/system/CRYP-248_pro_mode_transaction_details.e2e.ts
- packages/client/tests/system/CRYP-263_contact_details.e2e.ts
- packages/client/tests/system/CRYP-265_settings_bitcoin_wallet_details.e2e.ts
- packages/client/tests/system/CRYP-267_settings_ethereum_wallet_details.e2e.ts
- packages/client/tests/system/CRYP-30_ethereum_transaction_details.e2e.ts
- packages/client/tests/system/CRYP-32_saved_filters.e2e.ts
- packages/client/tests/system/CRYP-332_update_sign_up.e2e.ts
- packages/client/tests/system/CRYP-37_filter_ethereum_transactions_by_tag.e2e.ts
- packages/client/tests/system/CRYP-46_reset_password.e2e.ts
- packages/docs/system-test-recordings/system-test-recordings.md
TODO: The recordings file is all setup with the links for the new system tests. What is left is to record the runs and push the gifs to the repo with the correct names
> CRYP-000: Release 3 system tests

- packages/client/screens/account/AccountScreen.tsx
- packages/client/screens/reset-password/createNewPasswordScreen.tsx
Jira: https://cryptify.atlassian.net/browse/CRYP-341?atlOrigin=eyJpIjoiMGMyNzQxODhmNWFjNDdiNTllMDdjZDQwYThhYWE3ZTEiLCJwIjoiaiJ9
To match ui
> CRYP-341: Fixed reset password spelling on account and create new password

- packages/client/components/BackButton.tsx
- packages/client/navigation/index.tsx
- packages/client/screens/SignInScreen.tsx
- packages/client/screens/account/AccountPasswordScreen.tsx
- packages/client/screens/reset-password/createNewPasswordScreen.tsx
- packages/client/screens/reset-password/reset-password-sates/resetPasswordFailureScreen.tsx
- packages/client/screens/reset-password/reset-password-sates/resetPasswordSuccessScreen.tsx
- packages/client/screens/reset-password/resetPasswordEmailScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-349
- Fixed forgot password button spelling
- Fixed all reset password related screens that did not match the UI mockups
> CRYP-349: Fix incorrectly spelled forgot password button

- packages/client/screens/WalletSettingsScreen.tsx
JIRA : https://cryptify.atlassian.net/browse/CRYP-353?atlOrigin=eyJpIjoiNTBiZjhjMjBkOGRiNGM5ZGExM2YxNmMyNzQ0ODY0NTQiLCJwIjoiaiJ9
> CRYP-353-fixed edit wallet name buttons to match UI specs
