SOEN-490-Capstone/Cryptify

packages/client/App.tsx, packages/client/package.json, yarn.lock
- Add native base dependency
- Fix `react-native-web` version
`react-native-web` version 0.18.x deleted a function that is used by native-base. This pr adds native base and downgrades and pins `react-native-web` to version 0.17.x so that the packages are compatible
=> CRYP-49: Add native base and fix react-native-web version

packages/client/App.tsx, packages/client/screens/SignInScreen.tsx, packages/client/theme/components/button.ts, packages/client/theme/components/form-control.ts, packages/client/theme/components/input.ts, packages/client/theme/components/text.ts, packages/client/theme/extendTheme.tsx, packages/common/src/validations/password_schema.ts, packages/common/src/validations/sign_in_schema.ts
- Created custom theme files for each component used to match the UI mockups
- Refactored the sign in page to take into account these new additions
=> CRYP-51: Fix sign in page styling to match UI mockups

packages/client/screens/SignUpScreen.tsx, packages/common/src/validations/sign_up_schema.ts
- Refactored the sign up page to take incorporate custom component themes to match UI mockups
=> CRYP-49: Fix sign up page styling to match UI mockups

packages/api/src/authentication/authentication.service.ts, packages/api/src/users/users.service.ts, packages/client/App.tsx, packages/client/gateways/auth_gateway.ts, packages/client/gateways/request.ts, packages/client/screens/SignInScreen.tsx, packages/client/screens/SignUpScreen.tsx, packages/common/src/errors/error_messages.ts
- Add API error message for sign up and sign in
- Fix safe area and line height on sign up and sign in top text
- Refactor error messages to common
- Refactor request method to allow for different methods
=> CRYP-21: Add API error messages to sign up and sign in

packages/client/theme/components/button.ts, packages/client/theme/components/form-control.ts, packages/client/theme/components/input.ts, packages/client/theme/components/text.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-184
- Refactor the custom component themes (Text, Button, Input, FormErrorMessage) to use the custom typography
- Moving forward, there is no need to add the font size, font weight and line height CSS styling to the `Text` component
**Old**
```typescript
<Text style={styles.textStyle}>Text</Text>
textStyle: {
fontSize: 20,
lineHeight: 27,
fontWeight: "600,
}
```
**New**
```typescript
<Text size={"title3"} fontWeight={"semibold"}>Text</Text>
```
- Refactor all UI components to utilize the custom typography (will be done in a follow-up PR)
=> CRYP-184: Refactor custom component themes to use custom typography

packages/client/components/wallets-list/WalletsList.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-101
Previously when a new wallet was added it wouldnt show up on the home screen until the app was restarted because the page is cached so the api call would never happen again, and would only show through the setting page if you navigated away then back to it. Now anytime the page containing the wallets list comes into focus again we will make a new api request to get the users wallets.
=> CRYP-101: Update wallet list when new wallet is added

packages/client/components/wallets-list/WalletsList.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-101
- Wrong conditional check was being used to see if the wallets list was empty resulting in a blank page instead of icon and text
=> CRYP-101: Fix wallets list conditional check

.github/workflows/ci.yml, package.json, packages/btc-edge/test/integration/wallet_api.spec.ts, packages/client/components/AddressShareButton.tsx, packages/client/components/TransactionDetails.tsx, packages/client/components/transactions-list/TransactionListItem.tsx, packages/client/components/wallets-list/WalletsListAccordion.tsx, packages/client/navigation/index.tsx, packages/client/screens/WalletOverviewScreen.tsx, packages/client/screens/WalletQRCodeScreen.tsx, packages/client/services/currency_service.ts, packages/client/types.tsx, packages/common/jest-config-unit.json, packages/common/package.json, packages/common/src/utils/currency_utils.ts, packages/common/test/unit/currency_utils.spec.ts, yarn.lock
JIRA: https://cryptify.atlassian.net/browse/CRYP-120
- Create formal function that can parse eth and btc wallets but also transaction hashes
- Use new function to clean up a bunch of code that used improper ways of figuring out the currency type from an address
=> CRYP-120: refactor address validation to library

packages/btc-edge/src/gateways/so_chain_gateway.ts, packages/btc-edge/src/types/so_chain_responses.ts, packages/btc-edge/test/unit/gateways/so_chain_gateway.spec.ts, packages/eth-edge/src/services/alchemy_node_facade.service.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-226
- Fix ETH transactions being stored backwards
- Fix BTC transactions being stored backwards
- Implement BTC reverse transaction pooling to improve accuracy of MIMO transaction amounts
=> CRYP-226: fix transaction in and out flipped

packages/btc-edge/test/integration/base_api.spec.ts, packages/btc-edge/test/integration/wallet_api.spec.ts
There seems to be some issue with the websocket service starting up in the tests before the repository has made a connection with the DB. This issue doesn't appear when the application is actually running in dev or prod. For the time being the test can be skipped so it doesn't block others
=> CRYP-000: Skip failing test

packages/client/screens/NotificationsScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-41
- Fix typo
- Fix spacing on android
- Fix text spacing on all devices
- On Android the switch is smaller than the one on iOS but they take the same footprint so on Android the button is pushed to the left 10-15px more than on iOS, fixing this on Android would then make the iOS version look too far to the right. I've opted to just leave it as is for now, we can write some custom Android css rule to fix it if needed in the future.
=> CRYP-41: Fix styling on notifications page

packages/client/components/BackButton.tsx, packages/client/navigation/index.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-240
- The back button in the top navigation bar on iOS devices displays the correct `arrow-left` icon without a `Back` label (as shown in the UI mockups)
- The back button is by default displayed on all screens. To hide the back button on a specific screen, put `headerLeft: () => null` in the `options` prop for the associated screen (see `<HomeStack.Screen`)
=> CRYP-240: Fix incorrect back arrow button displayed on iOS devices

packages/client/components/transactions-list/TransactionListItem.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-275
- The header of both transaction details screen displays the correct date and time format `Mon DD, YYYY • 00:00 AM/PM` instead of `Monday`
=> CRYP-275: Fix incorrect date displayed in the header of transaction details screen

packages/client/components/wallets-list/WalletsListAccordion.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-339
- Aligned the total Bitcoin balance of all wallets in the accordion header to the right
=> CRYP-339: Fix Bitcoin balance in accordion header not properly aligned

packages/client/screens/add-wallet/add-wallet-states/AddWalletFormScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-336
- Changed the add wallet button on the `Add a Bitcoin Wallet` screen to `Add Bitcoin wallet` from `Add Bitcoin Wallet`
- Changed the add wallet button on the `Add an Ethereum Wallet` screen to `Add Bitcoin wallet` from `Add Ethereum Wallet`
=> CRYP-336: Fix incorrect button text in add Bitcoin/Ethereum wallet screens

packages/client/components/transaction-details/TransactionDetailsActionSheet.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-345
- The options action sheet in the transaction details screen is closed before navigating to the contacts screen when assigning a contact to a transaction
=> CRP-345: Fix transaction details options action sheet displaying in contacts screen

packages/client/screens/filters/FilterContactScreen.tsx, packages/client/theme/components/checkbox.ts, packages/client/theme/extendTheme.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-347
- The `Reset` button is no longer displayed in the `Filter by Contact` screen when there isn't a contact selected
- Add custom theme for checkbox component
- Update UI to match UI mockups
=> CRYP-347: Fix reset button in filter contact screen displaying when no contact selected

packages/client/components/TitleTextWithIcon.tsx, packages/client/navigation/index.tsx, packages/client/screens/HomeScreen.tsx, packages/client/screens/SignUpNotificationsScreen.tsx, packages/client/screens/WalletSettingsScreen.tsx, packages/client/screens/add-wallet/AddWalletScreen.tsx, packages/client/screens/add-wallet/AddWalletSelectionScreen.tsx, packages/client/screens/add-wallet/add-wallet-states/AddWalletFailureScreen.tsx, packages/client/screens/add-wallet/add-wallet-states/AddWalletSuccessScreen.tsx, packages/client/tests/system/CRYP-24_add_wallet.e2e.ts, packages/client/types.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-346
- The `Back to` button text now displays either `home` or `wallets` depending on which screen the `Add a Wallet` process started from
- Updated system tests
- Updated UI to match UI mockups
=> CRYP-346: Fix incorrect go back button text in add wallet success & failure screens

packages/client/components/contacts/CollapsibleFormSection.tsx, packages/client/components/contacts/ContactsForm.tsx, packages/client/screens/contacts/AddContactScreen.tsx, packages/client/screens/contacts/ContactsListScreen.tsx, packages/client/screens/contacts/EditContactScreen.tsx, packages/common/src/errors/error_messages.ts
JIRA: https://cryptify.atlassian.net/browse/CRYP-348
- The `Add another Bitcoin/Ethereum wallet` button will only display when there is at least 1 form field for their respective form sections in both the add and edit contact forms
- Updated all UIs to match UI mockups
- Fixed contact name error messages not displaying on the form according to the specs
=> CRYP-348: Fix add another Bitcoin/Ethereum wallet button always displaying in add contact form

packages/client/screens/TagsSettingsScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-350
- Edit button in settings tags list is only displayed when at least 1 tag has been added to the account
=> CRYP-350: Fix edit button displaying in tags list when no tags are added

packages/client/screens/filters/FilterTagScreen.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-351
- No tags message is now displayed when no tags are added to the user account
- Reset button only shows when at least 1 tag is selected
- The `Selected Transaction` section is not displayed if no tags are selected
=> CRYP-351: Fixed no tags messages not displaying in filter by tag screen

packages/client/components/SaveFilterActionSheet.tsx, packages/client/components/icons/light/falBookmark.tsx, packages/client/navigation/index.tsx, packages/client/screens/TagsSettingsScreen.tsx, packages/client/screens/TransactionsListScreen.tsx, packages/client/screens/filters/FilterContactScreen.tsx, packages/client/screens/filters/FilterDateScreen.tsx, packages/client/screens/filters/FilterScreen.tsx, packages/client/screens/filters/FilterTagScreen.tsx, packages/client/screens/filters/SavedFiltersScreen.tsx, packages/client/services/sort_service.ts, packages/client/tests/system/CRYP-32_saved_filters.e2e.ts, packages/client/types.tsx
JIRA: https://cryptify.atlassian.net/browse/CRYP-352
- Refactored `Filter by Transaction` to match UI mockups
- Moved `Filter by Date` to a separate screen
- Fixed saved filters not storing contacts and tags in the database
- Fixed the `Reset` button in the filter screen not properly resetting all filters across screens
- Fixed filter states not properly persisting between transaction list and filter screen(s)
- Updated tag filter badges in transaction list to match UI mockups
- Fix `Save this filter` not properly displaying/hiding 
- Refactor tag badge order to match specs
- Refactoring spacing/styling to match UI mockups
- Fixed all associated system tests
=> CRYP-352: Fix transaction filter screens to matching UI mockups
